apiVersion: v1
kind: Service
metadata:
  name: kiosk
  namespace: kiosk
  labels:
    app: kiosk
spec:
  type: NodePort
  selector:
    app: kiosk
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
